name: Pull Request Event
on:
  pull_request:
    types:
      - opened
    branches-ignore:
      - main
  workflow_dispatch:
jobs:
  PullRequestJob:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request
        run: echo "pull request opened"
