name: Sequential Execution 
on: workflow_dispatch
jobs:
  FirstJob:
    runs-on: k8s-runner
    steps:
      - name: First Job Executing
        run: echo "Executed"
  SecondJob:
    needs: [FirstJob]
    runs-on: k8s-runner
    steps:
      - name: Second Job Executing
        run: echo "done"
