name: Play Public YouTube Video

on: workflow_dispatch

jobs:
  play-video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install mpv
        run: |
          sudo apt-get update
          sudo apt-get install -y mpv

      - name: Play YouTube video 10 times
        run: |
          VIDEO_URL="https://www.youtube.com/shorts/B6ebIDCVXW8"
          for i in $(seq 1 10)
          do
              echo "Playing video - Attempt $i"
              mpv --no-video $VIDEO_URL  # This plays audio-only. Remove --no-video to play the full video
          done
