name: Run YouTube Video

on: workflow_dispatch

jobs:
  play-video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install mpv
        run: |
          sudo apt-get update
          sudo apt-get install -y mpv

      - name: Make shell script executable
        run: chmod +x play_video.sh

      - name: Run YouTube video 10 times
        run: ./play_video.sh
