name: Run YouTube Video

on: workflow_dispatch

jobs:
  run-video:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set execute permissions
      run: chmod +x ./curl.sh

    - name: Run YouTube video
      run: ./curl.sh
