name: Play Public YouTube Video

on: workflow_dispatch

jobs:
  play-video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install yt-dlp and mpv
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip mpv ffmpeg
          pip3 install yt-dlp

      - name: Download YouTube video
        run: |
          VIDEO_URL="https://www.youtube.com/watch?v=your_video_id"
          yt-dlp -f best -o video.mp4 $VIDEO_URL  # Downloads the best quality video

      - name: Play the video 10 times using mpv
        run: |
          for i in $(seq 1 10)
          do
              echo "Playing video - Attempt $i"
              mpv video.mp4
          done
